// Static data for Guest users (Zero-Latency Rendering)

export const STATIC_CATEGORIES = [
    { id: "IT", name: "IT" },
    { id: "HR", name: "HR" },
    { id: "Business", name: "Business" },
    { id: "Design", name: "Design" },
    { id: "Marketing", name: "Marketing" },
    { id: "Finance", name: "Finance" },
    { id: "AI", name: "AI" }
];

export const GUEST_EXPERTS = [
    {
        id: "guest-1",
        expertID: "guest-exp-1",
        name: "Dr. Sarah Chen",
        role: "Senior AI Researcher",
        industry: "AI",
        category: "AI",
        avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200",
        location: "San Francisco, CA",
        experience: "12+ years",
        skills: ["Machine Learning", "Neural Networks", "Python", "TensorFlow"],
        languages: ["English", "Mandarin"],
        mode: "Online",
        rating: 4.9,
        reviews: 124,
        price: "₹1200/hr",
        responseTime: "2h",
        successRate: 98,
        isVerified: true,
        isFeatured: true,
        company: "DeepMind",
        availability: { sessionDuration: 60 }
    },
    {
        id: "guest-2",
        expertID: "guest-exp-2",
        name: "James Wilson",
        role: "Product Director",
        industry: "Business",
        category: "Business",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200",
        location: "London, UK",
        experience: "15+ years",
        skills: ["Product Strategy", "Agile", "Team Leadership", "Growth"],
        languages: ["English"],
        mode: "Online",
        rating: 4.8,
        reviews: 89,
        price: "₹1500/hr",
        responseTime: "4h",
        successRate: 95,
        isVerified: true,
        isFeatured: false,
        company: "FinTech Corp",
        availability: { sessionDuration: 45 }
    },
    {
        id: "guest-3",
        expertID: "guest-exp-3",
        name: "Elena Rodriguez",
        role: "UX Design Lead",
        industry: "Design",
        category: "Design",
        avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200",
        location: "Barcelona, ES",
        experience: "8+ years",
        skills: ["UI/UX", "Figma", "User Research", "Prototyping"],
        languages: ["English", "Spanish"],
        mode: "Online",
        rating: 4.9,
        reviews: 215,
        price: "₹900/hr",
        responseTime: "1h",
        successRate: 100,
        isVerified: true,
        isFeatured: true,
        company: "DesignScale",
        availability: { sessionDuration: 60 }
    },
    {
        id: "guest-4",
        expertID: "guest-exp-4",
        name: "Michael Chang",
        role: "DevOps Architect",
        industry: "IT",
        category: "IT",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
        location: "Singapore",
        experience: "10+ years",
        skills: ["AWS", "Kubernetes", "CI/CD", "Terraform"],
        languages: ["English", "Mandarin"],
        mode: "Online",
        rating: 4.7,
        reviews: 67,
        price: "₹1800/hr",
        responseTime: "5h",
        successRate: 96,
        isVerified: true,
        isFeatured: false,
        company: "CloudSystems",
        availability: { sessionDuration: 30 }
    }
];
